[package]
name = "adventofcode"
version = "0.6.3"
authors = ["Felix Spöttel <1682504+fspoettel@users.noreply.github.com>"]
edition = "2021"
default-run = "adventofcode"
publish = false

[dependencies]
byte_set = "0.1.3"
itertools = "0.10.5"
pico-args = "0.5.0"
regex = "1.7.0"
tuple = "0.5.1"
